import { type NextPage } from "next";
import Head from "next/head";

const ProfilePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kwootter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-gradient-to-b from-[#091e20] to-[#051214]">
        <p className="text-xl font-bold text-white">Profile Page</p>
      </main>
    </>
  );
};

export default ProfilePage;
