import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
	const user = useUser();
	const { data, isLoading } = api.post.getAll.useQuery();
	if (isLoading) {
		return <div>is Loading..</div>;
	}

	if (!data) {
		return <div>Something went wrong</div>;
	}

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen justify-center bg-gradient-to-b from-[#17c3d2] to-[#1c454c]">
				<div className="h-full w-full md:max-w-2xl border-slate-400 border-x">
					<div className="flex">
						<div className="flex border-b border-slate-400 p-4">
							{!user.isSignedIn && (
								<div className="flex justify-center text-white border border-white p-2 rounded">
									<SignInButton />
								</div>
							)}
						</div>
						<div className="flex border-b border-slate-400 p-4">
							{!!user.isSignedIn && (
								<div className="flex justify-end text-white border border-white p-2 rounded">
									<SignOutButton />
								</div>
							)}
						</div>
					</div>
					<div className="flex flex-col">
						{[...data, ...data]?.map((post) => (
							<div className="p-4 border-b border-white" key={post.id}>
								{post.content}
							</div>
						))}
					</div>
				</div>
			</main>
		</>
	);
};

export default Home;
