import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
	const { data } = api.post.getAll.useQuery();
	const user = useUser();
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<div className="text-white border border-white p-2">
					{!user.isSignedIn && <SignInButton />}
					{!!user.isSignedIn && <SignOutButton />}
				</div>
				<div className="p-2 border border-white">
					{data?.map((post) => (
						<div className="p-1 mb-1 border border-white" key={post.id}>
							{post.content}
						</div>
					))}
				</div>
			</main>
		</>
	);
};

export default Home;
